### PR TITLE
Remove block() in reactive context

### PR DESCRIPTION
**Pull request by KyoosikLee**
Removed `block()`s inside reactive contexts. `block()` in reactive context made migration fail to release locks.

### CODE REVIEW

**Comment by KuliginStepan** [comment]
Thank you for PR! Can you provide some test for this case?

**Comment by KyoosikLee** [comment]
Yeah sure! But I was wondering... what Java version is this project using? java 8 or java 11?

**Comment by KuliginStepan** [comment]
The project is built on java 8.
https://github.com/KuliginStepan/mongration/blob/8b8908297d894045d9d3631cb182804adf15cfc1/build.gradle#L14

**Comment by KuliginStepan** [comment]
Merged in #17

**Pull request closed without merging**
